version: "3.7"

services:
  frontend_quiz:
    container_name: frontend_quiz
    build:
      context: ./src/frontend/quiz
      dockerfile: Dockerfile
    volumes:
      - quiz_app:/frontend_quiz/data
    ports:
      - 5151:5151
    tty: true

  gateway_api:
    container_name: gateway_api
    build:
      context: ./src/gateway_api_service
      dockerfile: Dockerfile
    volumes:
      - quiz_app:/gateway_api/data
    ports: 
      - 5000:5000
  
  user_service:
    container_name: user_service
    build:
      context: ./src/user_service
      dockerfile: Dockerfile
    volumes:
      - quiz_app:/user_service/data
    ports:
      - 8080:8080
  test_service:
    container_name: test_service
    build:
      context: ./src/test_service
      dockerfile: Dockerfile
    volumes:
      - quiz_app:/test_service/data
    ports:
      - 8081:8081

  subject_service:
    container_name: subject_service
    build:
      context: ./src/subject_service
      dockerfile: Dockerfile
    volumes:
      - quiz_app:/subject_service/data
    ports:
      - 8082:8082

volumes:
  quiz_app:
    

